<?php
/**
 * Title: Collection editorial panels
 * Slug: cartsfront/collection-panels
 * Categories: cartsfront
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"align": "wide", "className": "cartsfront-collection-grid cartsfront-section", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-grid cartsfront-section"><!-- wp:group {"align": "wide", "className": "cartsfront-collection-card", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-card"><!-- wp:group {"align": "wide", "className": "cartsfront-collection-art cartsfront-art-1", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-art cartsfront-art-1"></div><!-- /wp:group --><!-- wp:heading {"level": 3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Carry goods', 'cartsfront' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className": ""} --><p class=""><?php esc_html_e( 'For the everyday and the getting away.', 'cartsfront' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"align": "wide", "className": "cartsfront-collection-card", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-card"><!-- wp:group {"align": "wide", "className": "cartsfront-collection-art cartsfront-art-2", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-art cartsfront-art-2"></div><!-- /wp:group --><!-- wp:heading {"level": 3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Daily rituals', 'cartsfront' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className": ""} --><p class=""><?php esc_html_e( 'Small details. A little more considered.', 'cartsfront' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"align": "wide", "className": "cartsfront-collection-card", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-card"><!-- wp:group {"align": "wide", "className": "cartsfront-collection-art cartsfront-art-3", "layout": {"type": "default"}} --><div class="wp-block-group alignwide cartsfront-collection-art cartsfront-art-3"></div><!-- /wp:group --><!-- wp:heading {"level": 3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Home & desk', 'cartsfront' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className": ""} --><p class=""><?php esc_html_e( 'Make room for what matters.', 'cartsfront' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
